version: '3.5'
services:

  frontend:
    container_name: data-migration-interactor
    restart: always
    build:
      context: .
      dockerfile: Dockerfile-py
    tty: true 
    ports:
      - '5000:5000'
    depends_on:
      - "sql-parser"
    networks:
      - local
    #environment:  
    #  - FLASK_APP=app.py

  sql-parser:
    container_name: data-migration-sql-helper
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '9080:9080'
    networks:
      - local
      
networks:
  local:
    driver: bridge