FROM python:3

ARG VERSION=1.0

USER root

COPY /build/docker/scripts/ /scripts/

WORKDIR /scripts
RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 5000

#CMD [ "python", "./app.py" ]

CMD ["python", "-m", "flask", "run", "--host=0.0.0.0"]